positionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: "${self:custom.stage}.positions"
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 10
      WriteCapacityUnits: 10